name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # 修改为你的部署分支（通常为 main 或 master）

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
